marks=[78, 85, 62, 90, 55]
print("->Marks:",marks)
print("->Length of the list:",len(marks))
print("->First mark:",list[0])
print("->Last mark:",list[-1])
print("->Using slicing:",marks[1:4])
marks[2]=70
print("->Index 2 replaced:",marks)
marks[1:3]=[88,92]
print("->Index 1 to 3 replaced:",marks)
marks.append(76)
marks.insert(1,60)
marks.extend([81,84])
print("->After adding new marks:",marks)
marks.remove(55)
marks.pop(-1)
print("->After removing 55 amd last element:",marks)
print("->Printing each element using loop:")
for item in marks:print(item,end=" ")
passed_marks=[x for x in marks if x>=60]
print("->\nPassed marks:",passed_marks)
passed_marks.sort()
print("->Passed mark sorted in ascending order:",passed_marks)
passed_marks.sort(reverse=True)
print("->Passed mark sorted in descending order:",passed_marks)