monthly_sales=(12000, 15000, 11000, 18000, 16000, 14000)
print("->Monthly sales:",monthly_sales)
print("->Total number of months:",len(monthly_sales))
print("->First month sales:",monthly_sales[0])
print("->Last month sales:",monthly_sales[-1])
print("->Sales from index 1 to 4:",monthly_sales[1:4])
print("->Whether 15000 exists in the tuple:",15000 in monthly_sales)
print("->Looping through the tuple:")
for item in monthly_sales:print(" ",item,end=" ")
sales_list=list(monthly_sales)
sales_list.append(17000)
sales_list.remove(11000)
print("\n->After Converting to list,adding 17000 and removing 11000:\n",sales_list)
sales_tuple=tuple(sales_list)
a,b,*c=sales_tuple
print("->After Unpacking:","a=",a," b=",b," c=",c)
sorted_tuple=sorted(sales_tuple)
print("->Sorted tuple:",sorted_tuple)
print("->Highest sales:",sorted_tuple[-1])
print("->Lowest sales:",sorted_tuple[0])
